services:
  frontend:
    build:
      context: .
      target: runner
    command: bun run dev --hostname 0.0.0.0 --port 7100
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "7100:7100"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:7100
      - NEXT_PUBLIC_ENV=dev
      - ENV=dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
