"""Tests for post_update_node persistence via real Supabase, LLM, Qdrant, Neo4j."""

import uuid

import pytest

from app.agents.tutor_agent.nodes.post_update import post_update_node
from app.core.supabase import get_supabase_client
from tests.conftest import TEST_USER_ID


@pytest.mark.asyncio
async def test_update_memory_node_persistence():
    """QA-Memory: Verify post_update_node persists chat to real Supabase."""
    sb = get_supabase_client()
    session_id = str(uuid.uuid4())

    # Pre-create session for this test user
    sb.table("chat_sessions").insert(
        {"id": session_id, "user_id": TEST_USER_ID}
    ).execute()

    state = {
        "user_id": TEST_USER_ID,
        "jwt": "fake-jwt",  # not used by post_update_node
        "session_id": session_id,
        "user_input": "What is kanji?",
        "generation": "Kanji are Chinese characters used in Japanese writing.",
    }

    try:
        await post_update_node(state)

        # Verify messages were persisted in real Supabase
        msgs = sb.table("chat_messages").select("role, content").eq(
            "session_id", session_id
        ).order("created_at").execute()
        assert len(msgs.data) >= 2
        roles = [m["role"] for m in msgs.data]
        assert "user" in roles
        assert "assistant" in roles

        # Verify title was generated
        sess = sb.table("chat_sessions").select("title").eq("id", session_id).single().execute()
        assert sess.data["title"]  # non-empty title generated by LLM
    finally:
        sb.table("chat_messages").delete().eq("session_id", session_id).execute()
        sb.table("chat_sessions").delete().eq("id", session_id).execute()
