create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  avatar_color text default 'pink',
  bio text,
  native_language text,
  learning_goals text[] default '{}',
  role text not null default 'USER' check (role in ('USER', 'ADMIN')),
  level integer not null default 1,
  created_at timestamptz not null default now(),
  last_activity_at timestamptz
);

alter table public.users enable row level security;

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own"
on public.users
for select
to authenticated
using (id = auth.uid());

drop policy if exists "users_insert_own" on public.users;
create policy "users_insert_own"
on public.users
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create table if not exists public.custom_decks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  current_level integer not null default 1,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.custom_decks enable row level security;

drop policy if exists "custom_decks_select_own" on public.custom_decks;
create policy "custom_decks_select_own"
on public.custom_decks
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "custom_decks_insert_own" on public.custom_decks;
create policy "custom_decks_insert_own"
on public.custom_decks
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "custom_decks_update_own" on public.custom_decks;
create policy "custom_decks_update_own"
on public.custom_decks
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "custom_decks_delete_own" on public.custom_decks;
create policy "custom_decks_delete_own"
on public.custom_decks
for delete
to authenticated
using (user_id = auth.uid());

drop trigger if exists custom_decks_set_updated_at on public.custom_decks;
create trigger custom_decks_set_updated_at
before update on public.custom_decks
for each row
execute function public.set_updated_at();

create table if not exists public.custom_deck_items (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.custom_decks(id) on delete cascade,
  subject_id bigint not null,
  custom_level integer not null default 1,
  created_at timestamptz not null default now(),
  unique (deck_id, subject_id)
);

create index if not exists custom_deck_items_deck_id_idx
  on public.custom_deck_items (deck_id);

create index if not exists custom_deck_items_deck_level_idx
  on public.custom_deck_items (deck_id, custom_level);

alter table public.custom_deck_items enable row level security;

drop policy if exists "custom_deck_items_select_own" on public.custom_deck_items;
create policy "custom_deck_items_select_own"
on public.custom_deck_items
for select
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_items.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_items_insert_own" on public.custom_deck_items;
create policy "custom_deck_items_insert_own"
on public.custom_deck_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_items.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_items_update_own" on public.custom_deck_items;
create policy "custom_deck_items_update_own"
on public.custom_deck_items
for update
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_items.deck_id
      and d.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_items.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_items_delete_own" on public.custom_deck_items;
create policy "custom_deck_items_delete_own"
on public.custom_deck_items
for delete
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_items.deck_id
      and d.user_id = auth.uid()
  )
);

create table if not exists public.custom_deck_progress (
  id bigint generated by default as identity primary key,
  deck_id bigint not null,
  subject_id bigint not null,
  custom_stage integer not null default 0,
  custom_next_review_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (deck_id, subject_id),
  constraint custom_deck_progress_deck_item_fkey
    foreign key (deck_id, subject_id)
    references public.custom_deck_items(deck_id, subject_id)
    on delete cascade
);

create index if not exists custom_deck_progress_deck_id_idx
  on public.custom_deck_progress (deck_id);

create index if not exists custom_deck_progress_next_review_idx
  on public.custom_deck_progress (deck_id, custom_next_review_at);

alter table public.custom_deck_progress enable row level security;

drop policy if exists "custom_deck_progress_select_own" on public.custom_deck_progress;
create policy "custom_deck_progress_select_own"
on public.custom_deck_progress
for select
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_progress.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_progress_insert_own" on public.custom_deck_progress;
create policy "custom_deck_progress_insert_own"
on public.custom_deck_progress
for insert
to authenticated
with check (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_progress.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_progress_update_own" on public.custom_deck_progress;
create policy "custom_deck_progress_update_own"
on public.custom_deck_progress
for update
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_progress.deck_id
      and d.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_progress.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "custom_deck_progress_delete_own" on public.custom_deck_progress;
create policy "custom_deck_progress_delete_own"
on public.custom_deck_progress
for delete
to authenticated
using (
  exists (
    select 1
    from public.custom_decks d
    where d.id = custom_deck_progress.deck_id
      and d.user_id = auth.uid()
  )
);

drop trigger if exists custom_deck_progress_set_updated_at on public.custom_deck_progress;
create trigger custom_deck_progress_set_updated_at
before update on public.custom_deck_progress
for each row
execute function public.set_updated_at();

create table if not exists public.user_deck_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id bigint not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, deck_id)
);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'user_deck_preferences_deck_id_fkey'
      and conrelid = 'public.user_deck_preferences'::regclass
  ) then
    alter table public.user_deck_preferences
      drop constraint user_deck_preferences_deck_id_fkey;
  end if;

  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'custom_decks'
      and c.relkind = 'r'
  ) then
    alter table public.user_deck_preferences
      add constraint user_deck_preferences_deck_id_fkey
      foreign key (deck_id) references public.custom_decks(id) on delete cascade;
  end if;
end
$$;

alter table public.user_deck_preferences enable row level security;

drop policy if exists "user_deck_preferences_select_own" on public.user_deck_preferences;
create policy "user_deck_preferences_select_own"
on public.user_deck_preferences
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "user_deck_preferences_insert_own" on public.user_deck_preferences;
create policy "user_deck_preferences_insert_own"
on public.user_deck_preferences
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "user_deck_preferences_update_own" on public.user_deck_preferences;
create policy "user_deck_preferences_update_own"
on public.user_deck_preferences
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "user_deck_preferences_delete_own" on public.user_deck_preferences;
create policy "user_deck_preferences_delete_own"
on public.user_deck_preferences
for delete
to authenticated
using (user_id = auth.uid());

drop trigger if exists user_deck_preferences_set_updated_at on public.user_deck_preferences;
create trigger user_deck_preferences_set_updated_at
before update on public.user_deck_preferences
for each row
execute function public.set_updated_at();

create table if not exists public.knowledge_units (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  type text not null,
  character text,
  meaning text not null default '',
  level integer not null default 1,
  jlpt integer,
  jlpt_level integer,
  document_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists knowledge_units_type_level_idx
  on public.knowledge_units (type, level);

create table if not exists public.radical_details (
  ku_id uuid primary key references public.knowledge_units(id) on delete cascade,
  meaning_mnemonic text,
  image_url text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.kanji_details (
  ku_id uuid primary key references public.knowledge_units(id) on delete cascade,
  onyomi text[] default '{}',
  kunyomi text[] default '{}',
  meaning_mnemonic text,
  reading_mnemonic text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.vocabulary_details (
  ku_id uuid primary key references public.knowledge_units(id) on delete cascade,
  reading text,
  audio_url text,
  parts_of_speech text[] default '{}',
  meaning_mnemonic text,
  context_sentences jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.grammar_details (
  ku_id uuid primary key references public.knowledge_units(id) on delete cascade,
  structure text,
  explanation text,
  nuance text,
  cautions text,
  external_links jsonb not null default '[]'::jsonb,
  example_sentences jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.kanji_radicals (
  kanji_id uuid not null references public.knowledge_units(id) on delete cascade,
  radical_id uuid not null references public.knowledge_units(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (kanji_id, radical_id)
);

create table if not exists public.vocabulary_kanji (
  vocab_id uuid not null references public.knowledge_units(id) on delete cascade,
  kanji_id uuid not null references public.knowledge_units(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (vocab_id, kanji_id)
);

create table if not exists public.grammar_relations (
  grammar_id uuid not null references public.knowledge_units(id) on delete cascade,
  related_id uuid not null references public.knowledge_units(id) on delete cascade,
  type text,
  comparison_note text,
  created_at timestamptz not null default now(),
  primary key (grammar_id, related_id)
);

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  ku_id uuid references public.knowledge_units(id) on delete cascade,
  item_id uuid references public.knowledge_units(id) on delete cascade,
  facet text not null default 'meaning',
  type text not null default 'text',
  prompt text not null default '',
  question_text text,
  cloze_text_with_blanks text,
  correct_answers text[] not null default '{}',
  hints text[] default '{}',
  choices jsonb not null default '[]'::jsonb,
  explanation text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists questions_item_facet_idx
  on public.questions (coalesce(item_id, ku_id), facet);

create table if not exists public.sentences (
  id uuid primary key default gen_random_uuid(),
  japanese text,
  english text,
  romaji text,
  japanese_raw text,
  english_raw text,
  japanese_html text,
  english_html text,
  source text default 'user',
  jlpt_level integer,
  audio_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sentence_knowledge (
  sentence_id uuid not null references public.sentences(id) on delete cascade,
  ku_id uuid not null references public.knowledge_units(id) on delete cascade,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (sentence_id, ku_id)
);

create table if not exists public.cloze_sentence_cards (
  id uuid primary key default gen_random_uuid(),
  sentence_id uuid not null references public.sentences(id) on delete cascade,
  focus_ku_id uuid references public.knowledge_units(id) on delete set null,
  cloze_data jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  ku_id uuid references public.knowledge_units(id) on delete cascade,
  cloze_id uuid references public.cloze_sentence_cards(id) on delete cascade,
  card_type text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_fsrs_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_new_cards integer not null default 10,
  daily_review_limit integer not null default 100,
  learning_steps integer[] not null default array[1, 10],
  relearning_steps integer[] not null default array[10],
  graduation_interval integer not null default 1,
  easy_interval integer not null default 4,
  interval_modifier double precision not null default 1.0,
  show_answer_timer boolean not null default true,
  auto_play_audio boolean not null default false,
  w0 double precision not null default 0.4,
  w1 double precision not null default 0.6,
  w2 double precision not null default 2.2,
  w3 double precision not null default 10.9,
  w4 double precision not null default 5.8,
  w5 double precision not null default 0.93,
  w6 double precision not null default 0.94,
  w7 double precision not null default 0.86,
  w8 double precision not null default 1.01,
  w9 double precision not null default 1.05,
  w10 double precision not null default 0.94,
  w11 double precision not null default 0.74,
  w12 double precision not null default 0.46,
  w13 double precision not null default 0.27,
  w14 double precision not null default 0.42,
  w15 double precision not null default 0.36,
  w16 double precision not null default 0.29,
  w17 double precision not null default 1.2,
  w18 double precision not null default 0.25,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_learning_states (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ku_id uuid not null references public.knowledge_units(id) on delete cascade,
  facet text not null default 'meaning',
  state text not null default 'new',
  stability double precision not null default 0,
  difficulty double precision not null default 5,
  reps integer not null default 0,
  lapses integer not null default 0,
  last_review timestamptz,
  next_review timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, ku_id, facet)
);

create index if not exists user_learning_states_due_idx
  on public.user_learning_states (user_id, next_review);

create table if not exists public.user_fsrs_states (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id uuid not null references public.knowledge_units(id) on delete cascade,
  ku_id uuid generated always as (item_id) stored,
  item_type text not null default 'ku',
  facet text not null default 'primary',
  state text not null default 'new',
  stability double precision not null default 0,
  difficulty double precision not null default 5,
  reps integer not null default 0,
  lapses integer not null default 0,
  notes text,
  last_review timestamptz,
  next_review timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, item_id, facet)
);

create index if not exists user_fsrs_states_due_idx
  on public.user_fsrs_states (user_id, next_review);

create table if not exists public.fsrs_review_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ku_id uuid not null references public.knowledge_units(id) on delete cascade,
  facet text not null default 'meaning',
  rating integer not null,
  state text,
  stability double precision,
  difficulty double precision,
  interval_days double precision,
  reviewed_at timestamptz not null default now()
);

create table if not exists public.reading_configs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  exercises_per_session integer not null default 5,
  time_limit_minutes integer not null default 15,
  difficulty_level text not null default 'adaptive',
  jlpt_target integer,
  vocab_weight integer not null default 40,
  grammar_weight integer not null default 30,
  kanji_weight integer not null default 30,
  include_furigana boolean not null default true,
  include_translation boolean not null default false,
  passage_length text not null default 'medium',
  topic_preferences text[] not null default '{}',
  auto_generate boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  total_exercises integer not null default 0,
  completed_exercises integer not null default 0,
  correct_answers integer not null default 0,
  total_time_seconds integer not null default 0,
  score integer not null default 0,
  config_snapshot jsonb not null default '{}'::jsonb,
  generated_by text default 'system',
  generation_context jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_exercises (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.reading_sessions(id) on delete cascade,
  passage_ja text not null default '',
  passage_furigana text,
  passage_en text not null default '',
  passage_title text not null default '',
  difficulty_level text not null default 'adaptive',
  jlpt_level integer,
  topic text not null default 'daily_life',
  word_count integer not null default 0,
  featured_vocab_ids text[] not null default '{}',
  featured_grammar_ids text[] not null default '{}',
  featured_kanji_ids text[] not null default '{}',
  questions jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  time_spent_seconds integer not null default 0,
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  youtube_id text unique,
  title text not null,
  description text,
  channel_name text,
  thumbnail_url text,
  duration_seconds integer not null default 0,
  language text not null default 'ja',
  jlpt_level integer,
  jlpt_distribution jsonb not null default '{}'::jsonb,
  tags text[] not null default '{}',
  subtitles jsonb not null default '[]'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.video_subtitles (
  id uuid primary key default gen_random_uuid(),
  video_id uuid not null references public.videos(id) on delete cascade,
  start_time_ms integer not null,
  end_time_ms integer not null,
  text text not null,
  tokens jsonb not null default '[]'::jsonb,
  grammar_points jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.video_vocab_stats (
  id uuid primary key default gen_random_uuid(),
  video_id uuid not null references public.videos(id) on delete cascade,
  ku_id uuid references public.knowledge_units(id) on delete set null,
  surface text not null,
  reading text,
  frequency integer not null default 0,
  jlpt integer,
  meaning text,
  created_at timestamptz not null default now()
);

create table if not exists public.video_categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text not null default '#F4ACB7',
  icon text not null default '📚',
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_video_library (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  category_id uuid references public.video_categories(id) on delete set null,
  notes text,
  is_favorite boolean not null default false,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, video_id)
);

create table if not exists public.video_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  last_position_ms integer not null default 0,
  progress_percent integer not null default 0,
  completed boolean not null default false,
  watch_count integer not null default 0,
  last_watched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

create table if not exists public.user_saved_words (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ku_id uuid references public.knowledge_units(id) on delete set null,
  surface text not null,
  reading text,
  meaning text,
  jlpt integer,
  source_video_id uuid references public.videos(id) on delete set null,
  source_timestamp_ms integer,
  notes text,
  saved_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, surface)
);

create table if not exists public.user_grammar_bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ku_id uuid references public.knowledge_units(id) on delete cascade,
  item_id uuid generated always as (ku_id) stored,
  source_video_id uuid references public.videos(id) on delete set null,
  source_timestamp_ms integer,
  context_sentence text,
  notes text,
  bookmarked_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, ku_id)
);

create table if not exists public.video_dictation_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  status text not null default 'active',
  total_subtitles integer not null default 0,
  correct_count integer not null default 0,
  accuracy_percent integer not null default 0,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.video_dictation_attempts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.video_dictation_sessions(id) on delete cascade,
  subtitle_id text not null,
  user_input text not null,
  is_correct boolean not null default false,
  accuracy_score integer not null default 0,
  time_taken_ms integer not null default 0,
  attempts_count integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.speaking_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  target_difficulty text,
  difficulty text,
  status text not null default 'active',
  sentences jsonb not null default '[]'::jsonb,
  total_sentences integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.speaking_attempts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.speaking_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  sentence text not null default '',
  word text not null default '',
  score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  summary text,
  mode text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_message_actions (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.chat_messages(id) on delete cascade,
  action_type text not null,
  target_ku_id uuid references public.knowledge_units(id) on delete set null,
  target_sentence_id uuid references public.sentences(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.llm_usage_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  model text,
  endpoint text,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  estimated_cost_usd numeric(12, 6) not null default 0,
  latency_ms integer,
  success boolean not null default true,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.admin_roles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid references auth.users(id) on delete set null,
  admin_name text,
  action text not null,
  target_type text,
  target_id text,
  old_value jsonb,
  new_value jsonb,
  reason text,
  ip_address text,
  created_at timestamptz not null default now()
);

create table if not exists public.abuse_alerts (
  id uuid primary key default gen_random_uuid(),
  alert_type text not null,
  severity text not null default 'medium',
  user_id uuid references auth.users(id) on delete set null,
  user_name text,
  ip_address text,
  description text,
  evidence jsonb,
  status text not null default 'open',
  resolved_by uuid references auth.users(id) on delete set null,
  resolution_notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.user_suspensions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  suspension_type text not null,
  suspended_until timestamptz,
  is_active boolean not null default true,
  lifted_at timestamptz,
  lift_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.rate_limit_overrides (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  user_name text,
  ip_address text,
  scope text not null,
  endpoint_pattern text not null,
  max_requests_per_minute integer,
  max_requests_per_hour integer,
  max_requests_per_day integer,
  expires_at timestamptz not null,
  reason text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_jobs (
  id uuid primary key default gen_random_uuid(),
  job_type text not null,
  job_version integer not null default 1,
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  payload_hash text,
  status text not null default 'pending',
  processing_started_at timestamptz,
  processing_completed_at timestamptz,
  processing_attempts integer not null default 0,
  max_attempts integer not null default 3,
  result jsonb,
  error_message text,
  error_code text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  first_processed_at timestamptz,
  replay_count integer not null default 0
);

create table if not exists public.agent_job_events (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.agent_jobs(id) on delete cascade,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.idempotency_locks (
  key text primary key,
  scope text,
  locked_at timestamptz not null default now(),
  expires_at timestamptz,
  payload_hash text,
  response jsonb
);

create or replace view public.profiles
with (security_invoker = true)
as
select
  id,
  email,
  display_name,
  avatar_url,
  avatar_color,
  bio,
  native_language,
  learning_goals,
  role,
  level,
  created_at,
  last_activity_at
from public.users;

create or replace view public.vocab_kanji
with (security_invoker = true)
as
select *
from public.vocabulary_kanji;

create or replace view public.subjects
with (security_invoker = true)
as
select
  id,
  slug,
  type,
  character,
  meaning,
  level,
  jlpt,
  jlpt_level,
  created_at,
  updated_at
from public.knowledge_units;

alter table public.knowledge_units enable row level security;
alter table public.radical_details enable row level security;
alter table public.kanji_details enable row level security;
alter table public.vocabulary_details enable row level security;
alter table public.grammar_details enable row level security;
alter table public.kanji_radicals enable row level security;
alter table public.vocabulary_kanji enable row level security;
alter table public.grammar_relations enable row level security;
alter table public.questions enable row level security;
alter table public.sentences enable row level security;
alter table public.sentence_knowledge enable row level security;
alter table public.cloze_sentence_cards enable row level security;
alter table public.flashcards enable row level security;
alter table public.user_fsrs_settings enable row level security;
alter table public.user_learning_states enable row level security;
alter table public.user_fsrs_states enable row level security;
alter table public.fsrs_review_logs enable row level security;
alter table public.reading_configs enable row level security;
alter table public.reading_sessions enable row level security;
alter table public.reading_exercises enable row level security;
alter table public.videos enable row level security;
alter table public.video_subtitles enable row level security;
alter table public.video_vocab_stats enable row level security;
alter table public.video_categories enable row level security;
alter table public.user_video_library enable row level security;
alter table public.video_progress enable row level security;
alter table public.user_saved_words enable row level security;
alter table public.user_grammar_bookmarks enable row level security;
alter table public.video_dictation_sessions enable row level security;
alter table public.video_dictation_attempts enable row level security;
alter table public.speaking_sessions enable row level security;
alter table public.speaking_attempts enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_message_actions enable row level security;
alter table public.llm_usage_logs enable row level security;
alter table public.admin_roles enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.abuse_alerts enable row level security;
alter table public.user_suspensions enable row level security;
alter table public.rate_limit_overrides enable row level security;
alter table public.agent_jobs enable row level security;
alter table public.agent_job_events enable row level security;
alter table public.idempotency_locks enable row level security;

drop policy if exists "knowledge_units_public_read" on public.knowledge_units;
create policy "knowledge_units_public_read" on public.knowledge_units
for select to anon, authenticated using (true);

drop policy if exists "radical_details_public_read" on public.radical_details;
create policy "radical_details_public_read" on public.radical_details
for select to anon, authenticated using (true);

drop policy if exists "kanji_details_public_read" on public.kanji_details;
create policy "kanji_details_public_read" on public.kanji_details
for select to anon, authenticated using (true);

drop policy if exists "vocabulary_details_public_read" on public.vocabulary_details;
create policy "vocabulary_details_public_read" on public.vocabulary_details
for select to anon, authenticated using (true);

drop policy if exists "grammar_details_public_read" on public.grammar_details;
create policy "grammar_details_public_read" on public.grammar_details
for select to anon, authenticated using (true);

drop policy if exists "kanji_radicals_public_read" on public.kanji_radicals;
create policy "kanji_radicals_public_read" on public.kanji_radicals
for select to anon, authenticated using (true);

drop policy if exists "vocabulary_kanji_public_read" on public.vocabulary_kanji;
create policy "vocabulary_kanji_public_read" on public.vocabulary_kanji
for select to anon, authenticated using (true);

drop policy if exists "grammar_relations_public_read" on public.grammar_relations;
create policy "grammar_relations_public_read" on public.grammar_relations
for select to anon, authenticated using (true);

drop policy if exists "questions_public_read" on public.questions;
create policy "questions_public_read" on public.questions
for select to anon, authenticated using (true);

drop policy if exists "videos_public_read" on public.videos;
create policy "videos_public_read" on public.videos
for select to anon, authenticated using (true);

drop policy if exists "video_subtitles_public_read" on public.video_subtitles;
create policy "video_subtitles_public_read" on public.video_subtitles
for select to anon, authenticated using (true);

drop policy if exists "video_vocab_stats_public_read" on public.video_vocab_stats;
create policy "video_vocab_stats_public_read" on public.video_vocab_stats
for select to anon, authenticated using (true);

drop policy if exists "sentences_public_read" on public.sentences;
create policy "sentences_public_read" on public.sentences
for select to anon, authenticated using (true);

drop policy if exists "sentences_insert_own" on public.sentences;
create policy "sentences_insert_own" on public.sentences
for insert to authenticated with check (created_by = auth.uid() or created_by is null);

drop policy if exists "sentences_update_own" on public.sentences;
create policy "sentences_update_own" on public.sentences
for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists "sentence_knowledge_authenticated_all" on public.sentence_knowledge;
create policy "sentence_knowledge_authenticated_all" on public.sentence_knowledge
for all to authenticated using (true) with check (true);

drop policy if exists "cloze_sentence_cards_authenticated_all" on public.cloze_sentence_cards;
create policy "cloze_sentence_cards_authenticated_all" on public.cloze_sentence_cards
for all to authenticated using (true) with check (true);

drop policy if exists "flashcards_authenticated_all" on public.flashcards;
create policy "flashcards_authenticated_all" on public.flashcards
for all to authenticated using (true) with check (true);

drop policy if exists "user_fsrs_settings_own" on public.user_fsrs_settings;
create policy "user_fsrs_settings_own" on public.user_fsrs_settings
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_learning_states_own" on public.user_learning_states;
create policy "user_learning_states_own" on public.user_learning_states
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_fsrs_states_own" on public.user_fsrs_states;
create policy "user_fsrs_states_own" on public.user_fsrs_states
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "fsrs_review_logs_own" on public.fsrs_review_logs;
create policy "fsrs_review_logs_own" on public.fsrs_review_logs
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "reading_configs_own" on public.reading_configs;
create policy "reading_configs_own" on public.reading_configs
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "reading_sessions_own" on public.reading_sessions;
create policy "reading_sessions_own" on public.reading_sessions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "reading_exercises_own" on public.reading_exercises;
create policy "reading_exercises_own" on public.reading_exercises
for all to authenticated using (
  exists (
    select 1 from public.reading_sessions s
    where s.id = reading_exercises.session_id
      and s.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.reading_sessions s
    where s.id = reading_exercises.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "video_categories_own" on public.video_categories;
create policy "video_categories_own" on public.video_categories
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_video_library_own" on public.user_video_library;
create policy "user_video_library_own" on public.user_video_library
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "video_progress_own" on public.video_progress;
create policy "video_progress_own" on public.video_progress
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_saved_words_own" on public.user_saved_words;
create policy "user_saved_words_own" on public.user_saved_words
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_grammar_bookmarks_own" on public.user_grammar_bookmarks;
create policy "user_grammar_bookmarks_own" on public.user_grammar_bookmarks
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "video_dictation_sessions_own" on public.video_dictation_sessions;
create policy "video_dictation_sessions_own" on public.video_dictation_sessions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "video_dictation_attempts_own" on public.video_dictation_attempts;
create policy "video_dictation_attempts_own" on public.video_dictation_attempts
for all to authenticated using (
  exists (
    select 1 from public.video_dictation_sessions s
    where s.id = video_dictation_attempts.session_id
      and s.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.video_dictation_sessions s
    where s.id = video_dictation_attempts.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "speaking_sessions_own" on public.speaking_sessions;
create policy "speaking_sessions_own" on public.speaking_sessions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "speaking_attempts_own" on public.speaking_attempts;
create policy "speaking_attempts_own" on public.speaking_attempts
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "chat_sessions_own" on public.chat_sessions;
create policy "chat_sessions_own" on public.chat_sessions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "chat_messages_own" on public.chat_messages;
create policy "chat_messages_own" on public.chat_messages
for all to authenticated using (
  exists (
    select 1 from public.chat_sessions s
    where s.id = chat_messages.session_id
      and s.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.chat_sessions s
    where s.id = chat_messages.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "chat_message_actions_own" on public.chat_message_actions;
create policy "chat_message_actions_own" on public.chat_message_actions
for all to authenticated using (
  exists (
    select 1
    from public.chat_messages m
    join public.chat_sessions s on s.id = m.session_id
    where m.id = chat_message_actions.message_id
      and s.user_id = auth.uid()
  )
) with check (
  exists (
    select 1
    from public.chat_messages m
    join public.chat_sessions s on s.id = m.session_id
    where m.id = chat_message_actions.message_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "llm_usage_logs_own" on public.llm_usage_logs;
create policy "llm_usage_logs_own" on public.llm_usage_logs
for select to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists "admin_roles_admin_read" on public.admin_roles;
create policy "admin_roles_admin_read" on public.admin_roles
for select to authenticated using (public.is_admin());

drop policy if exists "admin_audit_logs_admin_all" on public.admin_audit_logs;
create policy "admin_audit_logs_admin_all" on public.admin_audit_logs
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "abuse_alerts_admin_all" on public.abuse_alerts;
create policy "abuse_alerts_admin_all" on public.abuse_alerts
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "user_suspensions_admin_all" on public.user_suspensions;
create policy "user_suspensions_admin_all" on public.user_suspensions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "rate_limit_overrides_admin_all" on public.rate_limit_overrides;
create policy "rate_limit_overrides_admin_all" on public.rate_limit_overrides
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "agent_jobs_own_select" on public.agent_jobs;
create policy "agent_jobs_own_select" on public.agent_jobs
for select to authenticated using (created_by = auth.uid());

drop policy if exists "agent_jobs_own_insert" on public.agent_jobs;
create policy "agent_jobs_own_insert" on public.agent_jobs
for insert to authenticated with check (created_by = auth.uid());

drop policy if exists "agent_jobs_own_update" on public.agent_jobs;
create policy "agent_jobs_own_update" on public.agent_jobs
for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists "agent_job_events_own_select" on public.agent_job_events;
create policy "agent_job_events_own_select" on public.agent_job_events
for select to authenticated using (
  exists (
    select 1 from public.agent_jobs j
    where j.id = agent_job_events.job_id
      and j.created_by = auth.uid()
  )
);

drop policy if exists "agent_job_events_own_insert" on public.agent_job_events;
create policy "agent_job_events_own_insert" on public.agent_job_events
for insert to authenticated with check (
  exists (
    select 1 from public.agent_jobs j
    where j.id = agent_job_events.job_id
      and j.created_by = auth.uid()
  )
);

drop trigger if exists knowledge_units_set_updated_at on public.knowledge_units;
create trigger knowledge_units_set_updated_at before update on public.knowledge_units for each row execute function public.set_updated_at();

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at before update on public.questions for each row execute function public.set_updated_at();

drop trigger if exists sentences_set_updated_at on public.sentences;
create trigger sentences_set_updated_at before update on public.sentences for each row execute function public.set_updated_at();

drop trigger if exists user_fsrs_settings_set_updated_at on public.user_fsrs_settings;
create trigger user_fsrs_settings_set_updated_at before update on public.user_fsrs_settings for each row execute function public.set_updated_at();

drop trigger if exists user_learning_states_set_updated_at on public.user_learning_states;
create trigger user_learning_states_set_updated_at before update on public.user_learning_states for each row execute function public.set_updated_at();

drop trigger if exists user_fsrs_states_set_updated_at on public.user_fsrs_states;
create trigger user_fsrs_states_set_updated_at before update on public.user_fsrs_states for each row execute function public.set_updated_at();

drop trigger if exists reading_configs_set_updated_at on public.reading_configs;
create trigger reading_configs_set_updated_at before update on public.reading_configs for each row execute function public.set_updated_at();

drop trigger if exists reading_sessions_set_updated_at on public.reading_sessions;
create trigger reading_sessions_set_updated_at before update on public.reading_sessions for each row execute function public.set_updated_at();

drop trigger if exists reading_exercises_set_updated_at on public.reading_exercises;
create trigger reading_exercises_set_updated_at before update on public.reading_exercises for each row execute function public.set_updated_at();

drop trigger if exists videos_set_updated_at on public.videos;
create trigger videos_set_updated_at before update on public.videos for each row execute function public.set_updated_at();

drop trigger if exists video_categories_set_updated_at on public.video_categories;
create trigger video_categories_set_updated_at before update on public.video_categories for each row execute function public.set_updated_at();

drop trigger if exists user_video_library_set_updated_at on public.user_video_library;
create trigger user_video_library_set_updated_at before update on public.user_video_library for each row execute function public.set_updated_at();

drop trigger if exists video_progress_set_updated_at on public.video_progress;
create trigger video_progress_set_updated_at before update on public.video_progress for each row execute function public.set_updated_at();

drop trigger if exists user_saved_words_set_updated_at on public.user_saved_words;
create trigger user_saved_words_set_updated_at before update on public.user_saved_words for each row execute function public.set_updated_at();

drop trigger if exists user_grammar_bookmarks_set_updated_at on public.user_grammar_bookmarks;
create trigger user_grammar_bookmarks_set_updated_at before update on public.user_grammar_bookmarks for each row execute function public.set_updated_at();

drop trigger if exists video_dictation_sessions_set_updated_at on public.video_dictation_sessions;
create trigger video_dictation_sessions_set_updated_at before update on public.video_dictation_sessions for each row execute function public.set_updated_at();

drop trigger if exists speaking_sessions_set_updated_at on public.speaking_sessions;
create trigger speaking_sessions_set_updated_at before update on public.speaking_sessions for each row execute function public.set_updated_at();

drop trigger if exists chat_sessions_set_updated_at on public.chat_sessions;
create trigger chat_sessions_set_updated_at before update on public.chat_sessions for each row execute function public.set_updated_at();

drop trigger if exists agent_jobs_set_updated_at on public.agent_jobs;
create trigger agent_jobs_set_updated_at before update on public.agent_jobs for each row execute function public.set_updated_at();
