/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Memory-augmented chat (non-streaming).
         *
         *     Architecture Note:
         *       Auth is handled by Next.js/Supabase. user_id in request body
         *       is trusted to have been validated by the BFF layer.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Streaming version of /chat using the new iterative LangGraph.
         */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Proxy session creation to Domain Service.
         */
        post: operations["create_session_api_v1_memory_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Proxy session listing to Domain Service.
         */
        get: operations["list_sessions_api_v1_memory_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Proxy session detail to Domain Service.
         */
        get: operations["get_session_api_v1_memory_session__session_id__get"];
        put?: never;
        post?: never;
        /**
         * End Session
         * @description Delete session via Domain Service.
         */
        delete: operations["end_session_api_v1_memory_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Chat Context
         * @description Primary chatbot integration endpoint.
         */
        post: operations["get_chat_context_api_v1_memory_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/episodic/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Episodic
         * @description Search episodic memory.
         */
        post: operations["search_episodic_api_v1_memory_episodic_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/episodic/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Episodic
         * @description Add episodic memory.
         */
        post: operations["add_episodic_api_v1_memory_episodic_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/episodic/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget Episodic
         * @description Delete a specific episodic memory.
         */
        delete: operations["forget_episodic_api_v1_memory_episodic__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/episodic/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Episodic
         * @description Clear all episodic memories for a user.
         */
        delete: operations["clear_episodic_api_v1_memory_episodic_clear_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/semantic/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Semantic
         * @description Search semantic memory.
         */
        post: operations["search_semantic_api_v1_memory_semantic_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/semantic/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Semantic
         * @description Add semantic memory nodes and relationships.
         */
        post: operations["add_semantic_api_v1_memory_semantic_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/semantic/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Semantic
         * @description Clear all semantic memory for a user.
         */
        delete: operations["clear_semantic_api_v1_memory_semantic_clear_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Get user profile.
         */
        get: operations["get_user_profile_api_v1_memory_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Reading Session
         * @description Pure Agent Runtime version of Session Creation.
         *     1. Fetches config from Domain.
         *     2. Fetches learning context from Domain.
         *     3. Generates content via LLM Agents.
         *     4. Persists results back to Domain.
         */
        post: operations["create_reading_session_api_v1_reading_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Detailed */
        get: operations["health_detailed_api_v1_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/consolidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Consolidation */
        post: operations["run_consolidation_api_v1_memory_consolidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/test/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Test Data */
        post: operations["seed_test_data_api_v1_memory_test_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/test/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Test Data */
        delete: operations["clear_test_data_api_v1_memory_test_clear_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddEpisodicRequest */
        AddEpisodicRequest: {
            /** User Id */
            user_id: string;
            /** Text */
            text: string;
        };
        /** AddEpisodicResponse */
        AddEpisodicResponse: {
            /** User Id */
            user_id: string;
            /** Text */
            text: string;
            /** Id */
            id: string;
        };
        /** AddSemanticRequest */
        AddSemanticRequest: {
            /** User Id */
            user_id: string;
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Relationships */
            relationships: components["schemas"]["Relationship"][];
        };
        /** AddSemanticResponse */
        AddSemanticResponse: {
            /** User Id */
            user_id: string;
            /** Nodes Added */
            nodes_added: number;
            /** Relationships Added */
            relationships_added: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * User Id
             * @description User UUID — must match the authenticated token subject.
             */
            user_id: string;
            /**
             * Message
             * @description Max 4000 characters (~1000 tokens).
             */
            message: string;
            /**
             * Session Id
             * @description Session ID for thread continuity. If omitted, no session context is used.
             */
            session_id?: string | null;
            /**
             * Tts Enabled
             * @description If True, the agent will generate audio for the response.
             * @default false
             */
            tts_enabled: boolean;
        };
        /** ChatResponse */
        ChatResponse: {
            /** User Id */
            user_id: string;
            /** Session Id */
            session_id?: string | null;
            /** Message */
            message: string;
            /** Response */
            response: string;
            /**
             * Episodic Context
             * @default
             */
            episodic_context: string;
            /**
             * Semantic Context
             * @default
             */
            semantic_context: string;
            /**
             * Thread Context
             * @default
             */
            thread_context: string;
        };
        /** ClearResponse */
        ClearResponse: {
            /** User Id */
            user_id: string;
            /** Message */
            message: string;
        };
        /** ConsolidationResult */
        ConsolidationResult: {
            /** User Id */
            user_id: string;
            /** Memories Before */
            memories_before: number;
            /** Memories After */
            memories_after: number;
            /** Batches Merged */
            batches_merged: number;
            /** Message */
            message: string;
        };
        /** ContextRequest */
        ContextRequest: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Max Episodic
             * @default 3
             */
            max_episodic: number;
        };
        /**
         * ContextResponse
         * @description Ready-to-inject context block for a chatbot system prompt.
         *     Concatenate `system_prompt_block` before your system message.
         */
        ContextResponse: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
            /** System Prompt Block */
            system_prompt_block: string;
            /**
             * Episodic Memories
             * @default []
             */
            episodic_memories: components["schemas"]["EpisodicMemory"][];
            /**
             * Semantic Facts
             * @default []
             */
            semantic_facts: {
                [key: string]: unknown;
            }[];
            /**
             * User Profile Snippet
             * @default
             */
            user_profile_snippet: string;
            /**
             * Thread History
             * @default []
             */
            thread_history: components["schemas"]["SessionMessage"][];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Config Override */
            config_override?: {
                [key: string]: unknown;
            } | null;
            /** Topics */
            topics?: string[] | null;
        };
        /** EpisodicMemory */
        EpisodicMemory: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Score */
            score?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** EpisodicSearchRequest */
        EpisodicSearchRequest: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
            /**
             * K
             * @default 3
             */
            k: number;
        };
        /** EpisodicSearchResponse */
        EpisodicSearchResponse: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["EpisodicMemory"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Qdrant */
            qdrant: string;
            /** Neo4J */
            neo4j: string;
            /**
             * Db
             * @default ok
             */
            db: string;
            /**
             * Degraded
             * @default []
             */
            degraded: string[];
        };
        /** Node */
        Node: {
            /**
             * Id
             * @description Unique identifier — a person's name, company ticker, or concept.
             */
            id: string;
            /**
             * Type
             * @description Node type, e.g. 'User', 'Company', 'InvestmentPhilosophy'.
             */
            type: string;
        };
        /** Relationship */
        Relationship: {
            /** @description Source node. */
            source: components["schemas"]["Node"];
            /** @description Target node. */
            target: components["schemas"]["Node"];
            /**
             * Type
             * @description Relationship type, e.g. 'INTERESTED_IN', 'HAS_GOAL'.
             */
            type: string;
        };
        /** SemanticSearchRequest */
        SemanticSearchRequest: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
        };
        /** SemanticSearchResponse */
        SemanticSearchResponse: {
            /** User Id */
            user_id: string;
            /** Query */
            query: string;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** SessionMessage */
        SessionMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** UserProfile */
        UserProfile: {
            /** User Id */
            user_id: string;
            /** Name */
            name?: string | null;
            /**
             * Preferences
             * @default []
             */
            preferences: string[];
            /**
             * Goals
             * @default []
             */
            goals: string[];
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Facts
             * @default []
             */
            facts: string[];
            /**
             * Raw Triples
             * @default []
             */
            raw_triples: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_memory_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_api_v1_memory_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_api_v1_memory_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_v1_memory_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_context_api_v1_memory_context_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_episodic_api_v1_memory_episodic_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodicSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodicSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_episodic_api_v1_memory_episodic_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEpisodicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddEpisodicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_episodic_api_v1_memory_episodic__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_episodic_api_v1_memory_episodic_clear_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResponse"];
                };
            };
        };
    };
    search_semantic_api_v1_memory_semantic_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_semantic_api_v1_memory_semantic_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSemanticRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddSemanticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_semantic_api_v1_memory_semantic_clear_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResponse"];
                };
            };
        };
    };
    get_user_profile_api_v1_memory_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    create_reading_session_api_v1_reading_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_detailed_api_v1_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_consolidation_api_v1_memory_consolidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsolidationResult"];
                };
            };
        };
    };
    seed_test_data_api_v1_memory_test_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    clear_test_data_api_v1_memory_test_clear_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResponse"];
                };
            };
        };
    };
}
